In [1]:
from pandas import HDFStore 
from pandas import (
    DataFrame, HDFStore
)
import pandas as pd
import numpy as np
import h5py
import glob
import os
import codecs

In [31]:
h5new = HDFStore('pems_all_2022.h5')
df_new = h5new['speed']
#df
h5all.close()
h5all = HDFStore('pems-bay.h5')
df = h5all['speed']
df

sensor_id            400001  400017  400030  400040  400045  400052  400057  \
2017-01-01 00:00:00    71.4    67.8    70.5    67.4    68.8    66.6    66.8   
2017-01-01 00:05:00    71.6    67.5    70.6    67.5    68.7    66.6    66.8   
2017-01-01 00:10:00    71.6    67.6    70.2    67.4    68.7    66.1    66.8   
2017-01-01 00:15:00    71.1    67.5    70.3    68.0    68.5    66.7    66.6   
2017-01-01 00:20:00    71.7    67.8    70.2    68.1    68.4    66.9    66.1   
...                     ...     ...     ...     ...     ...     ...     ...   
2017-06-30 23:35:00    70.9    66.3    68.4    61.0    61.8    66.9    66.0   
2017-06-30 23:40:00    71.3    66.6    68.7    60.9    62.0    66.2    66.5   
2017-06-30 23:45:00    71.4    66.9    68.1    61.1    62.0    66.7    65.8   
2017-06-30 23:50:00    72.2    66.5    68.0    61.1    62.5    65.8    67.1   
2017-06-30 23:55:00    71.5    66.2    68.4    61.5    62.8    66.1    67.7   

sensor_id            400059  400065  400069  ...  409525  409526  409528  \
2017-01-01 00:00:00    68.0    66.8    69.0  ...    68.8    67.9    68.8   
2017-01-01 00:05:00    67.8    66.5    68.2  ...    68.4    67.3    68.4   
2017-01-01 00:10:00    67.8    66.2    67.8  ...    68.4    67.4    68.4   
2017-01-01 00:15:00    67.7    65.9    67.8  ...    68.5    67.5    68.5   
2017-01-01 00:20:00    67.7    66.1    67.8  ...    68.5    67.7    68.5   
...                     ...     ...     ...  ...     ...     ...     ...   
2017-06-30 23:35:00    67.4    65.4    69.3  ...    64.6    66.8    64.7   
2017-06-30 23:40:00    68.2    64.9    69.1  ...    65.1    67.3    64.8   
2017-06-30 23:45:00    68.2    64.2    69.1  ...    64.9    66.5    64.6   
2017-06-30 23:50:00    68.3    64.0    67.3  ...    64.1    65.9    64.8   
2017-06-30 23:55:00    68.4    64.9    68.0  ...    64.3    66.5    64.8   

sensor_id            409529  413026  413845  413877  413878  414284  414694  
2017-01-01 00:00:00    68.0    69.2    68.9    70.4    68.8    71.1    68.0  
2017-01-01 00:05:00    67.6    70.4    68.8    70.1    68.4    70.8    67.4  
2017-01-01 00:10:00    67.5    70.2    68.3    69.8    68.4    70.5    67.9  
2017-01-01 00:15:00    67.5    70.4    68.7    70.2    68.4    70.8    67.6  
2017-01-01 00:20:00    67.4    69.6    69.1    70.0    68.4    71.0    67.9  
...                     ...     ...     ...     ...     ...     ...     ...  
2017-06-30 23:35:00    61.1    68.4    61.4    70.5    68.2    71.6    66.2  
2017-06-30 23:40:00    60.8    69.8    62.2    69.4    68.6    71.6    68.4  
2017-06-30 23:45:00    61.3    69.5    63.8    70.6    68.4    71.6    66.6  
2017-06-30 23:50:00    61.3    69.6    64.2    70.2    68.7    71.6    68.4  
2017-06-30 23:55:00    60.9    70.9    63.4    70.3    68.7    71.6    68.0  

[52116 rows x 325 columns]

In [67]:
#time_ind, time_in_day.shape
from dateutil.parser import parse
from datetime import datetime
date = df_new.index.values[0]
# date

date_time_str = '01/13/2022 00:00:00'

def parse_time(date):
    date_time_obj = datetime.strptime(date, '%m/%d/%Y %H:%M:%S').strftime('%Y-%m-%d %H:%M:%S')
    return date_time_obj

In [76]:
date_array = df_new.index.values
date2 = '01/13/2022 00:00:00'
date_array_new = np.array(list(map(parse_time, date_array)))
#date_array_new = parse_time(date2)
regulared_index_value = date_array_new.astype("datetime64[ns]")

In [71]:
date = df.index.values
date

array(['2017-01-01T00:00:00.000000000', '2017-01-01T00:05:00.000000000',
       '2017-01-01T00:10:00.000000000', ...,
       '2017-06-30T23:45:00.000000000', '2017-06-30T23:50:00.000000000',
       '2017-06-30T23:55:00.000000000'], dtype='datetime64[ns]')

In [78]:
df_new_regular = df_new
df_new_regular = df_new_regular.set_axis(regulared_index_value)
df_new_regular

sensor_id            400001  400017  400030  400040  400045  400052  400057  \
2022-01-01 00:00:00    71.8    68.1    68.1    67.9    68.1    68.8    68.2   
2022-01-01 00:05:00    71.1    68.0    68.1    67.4    68.0    68.7    68.0   
2022-01-01 00:10:00    70.9    68.0    68.1    67.7    68.0    68.5    68.0   
2022-01-01 00:15:00    71.3    67.8    68.2    67.6    67.8    69.0    67.9   
2022-01-01 00:20:00    70.7    67.8    68.0    67.3    67.8    68.0    67.9   
...                     ...     ...     ...     ...     ...     ...     ...   
2022-06-30 23:35:00    71.1    64.9    68.7    68.3    67.7    66.6    67.3   
2022-06-30 23:40:00    71.4    64.7    67.6    67.5    67.8    66.1    67.8   
2022-06-30 23:45:00    71.4    64.8    67.0    66.9    67.7    66.8    67.1   
2022-06-30 23:50:00    72.5    64.4    68.3    67.7    67.8    67.1    67.7   
2022-06-30 23:55:00    72.2    64.7    66.8    68.1    67.8    66.7    67.1   

sensor_id            400059  400065  400069  ...  409525  409526  409528  \
2022-01-01 00:00:00    68.2    66.7    69.8  ...    67.6    68.2    66.2   
2022-01-01 00:05:00    68.2    66.4    69.1  ...    67.7    68.0    66.5   
2022-01-01 00:10:00    67.3    66.5    69.7  ...    67.3    68.0    66.1   
2022-01-01 00:15:00    67.7    66.1    68.4  ...    67.7    67.9    66.6   
2022-01-01 00:20:00    67.6    66.6    66.9  ...    67.7    67.9    65.5   
...                     ...     ...     ...  ...     ...     ...     ...   
2022-06-30 23:35:00    59.1    67.0    48.1  ...    64.5    67.7    65.7   
2022-06-30 23:40:00    59.3    66.5    46.8  ...    64.4    67.8    64.8   
2022-06-30 23:45:00    59.0    66.8    49.1  ...    63.5    67.8    65.2   
2022-06-30 23:50:00    59.4    66.8    49.2  ...    64.4    67.8    64.8   
2022-06-30 23:55:00    61.8    66.1    48.1  ...    64.5    67.8    65.3   

sensor_id            409529  413026  413845  413877  413878  414284  414694  
2022-01-01 00:00:00    68.2    72.4    68.7    69.8    68.3    71.4    67.8  
2022-01-01 00:05:00    68.0    72.6    68.7    70.2    68.2    71.3    68.4  
2022-01-01 00:10:00    68.0    72.1    67.9    70.1    68.0    71.0    67.5  
2022-01-01 00:15:00    67.9    71.5    67.9    69.9    68.0    70.4    67.6  
2022-01-01 00:20:00    67.9    70.4    68.8    70.4    67.5    70.8    68.0  
...                     ...     ...     ...     ...     ...     ...     ...  
2022-06-30 23:35:00    67.7    71.9    67.7    68.2    67.6    70.9    66.4  
2022-06-30 23:40:00    67.8    70.3    69.5    67.7    66.5    70.1    67.6  
2022-06-30 23:45:00    67.8    70.9    69.3    67.9    66.9    70.7    66.9  
2022-06-30 23:50:00    67.8    69.7    69.5    67.8    67.4    71.0    67.8  
2022-06-30 23:55:00    67.8    71.6    68.4    67.6    67.2    70.8    66.6  

[51649 rows x 319 columns]

In [93]:
#df_new_index = df_new_regular.index.values
df_new_index.shape

(51649,)

In [81]:
#df = pd.read_hdf('pems_all_2022.h5', 'speed')
# 0 is the latest observed sample.
x_offsets = np.sort(
# np.concatenate(([-week_size + 1, -day_size + 1], np.arange(-11, 1, 1)))
np.concatenate([-2+1, ], (np.arange(-11, 1, 1))))
#[-11 , -10, -9 ...0]
# Predict the next one hour
y_offsets = np.sort(np.arange(1, 13, 1))
#[1, 2, 3, 4, ...12]
# x_offsets, y_offsets

In [140]:
k_offsets = np.sort(np.arange(-11, 1, 1))
k_offsets,x_offsets

(array([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]),
 array([-11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0]))

In [106]:
#num_samples, num_nodes = df.shape
num_samples, num_nodes = df_new_regular.shape
data = np.expand_dims(df_new_regular.values, axis=-1)# slice by rows
data_list = [data]
time_ind = (df_new_regular.index.values - df_new_regular.index.values.astype("datetime64[D]")) / np.timedelta64(1, "D")
time_in_day = np.tile(time_ind, [1, num_nodes, 1]).transpose((2, 1, 0))

In [174]:
#data
#df_new_regular.index.values 
#a = (df_new_regular.index.values - df_new_regular.index.values.astype("datetime64[D]"))/np.timedelta64(1, "D")
#len(np. unique(a))
12*24

288

In [107]:
data_list.append(time_in_day)
data = np.concatenate(data_list, axis=-1)

In [112]:
#data contains 51649 rows, [319,2] elemments, 319 sensors with [speed, time]
#data[0].shape 

(319, 2)

In [118]:
# epoch_len = num_samples + min(x_offsets) - max(y_offsets)
x, y = [], []
# t is the index of the last observation.
min_t = abs(min(x_offsets))#11
max_t = abs(num_samples - abs(max(y_offsets)))  # Exclusive 51649 - 12
for t in range(min_t, max_t):#11 to 51649 - 12
    x_t = data[t + x_offsets, ...] #[0-11, ...], [1-12, ...]
    y_t = data[t + y_offsets, ...]#[11+[1,2,3,...,12], ...]
    x.append(x_t)
    y.append(y_t)
x = np.stack(x, axis=0)
y = np.stack(y, axis=0)

In [160]:
#min_t, max_t[0-11, ...]
data[80, ...]

array([[70.7       ,  0.27777778],
       [67.9       ,  0.27777778],
       [69.        ,  0.27777778],
       [67.3       ,  0.27777778],
       [67.9       ,  0.27777778],
       [67.8       ,  0.27777778],
       [68.        ,  0.27777778],
       [66.9       ,  0.27777778],
       [65.5       ,  0.27777778],
       [43.7       ,  0.27777778],
       [68.1       ,  0.27777778],
       [67.2       ,  0.27777778],
       [67.9       ,  0.27777778],
       [66.2       ,  0.27777778],
       [68.4       ,  0.27777778],
       [67.8       ,  0.27777778],
       [68.        ,  0.27777778],
       [66.7       ,  0.27777778],
       [69.8       ,  0.27777778],
       [68.4       ,  0.27777778],
       [68.4       ,  0.27777778],
       [68.        ,  0.27777778],
       [68.        ,  0.27777778],
       [61.6       ,  0.27777778],
       [67.9       ,  0.27777778],
       [67.4       ,  0.27777778],
       [68.9       ,  0.27777778],
       [68.        ,  0.27777778],
       [66.4       ,

In [143]:
check = np.expand_dims(df_new_regular.values, axis=-1)

In [145]:
def generate_data(df, x_length, y_length):
    n_samples, n_nodes = df.shape
    x_offsets = np.sort(np.arange(-x_length+1, 1, 1))
    y_offsets = np.sort(np.arange(1, y_length+1, 1))

    # Slice df by rows(different time slot)
    # This only contain the speed data for 319 sensors at the same time.
    data = np.expand_dims(df.values, axis=-1)
    data_list = [data]

    # Rewrite datetime format into numbers.
    # And pivoted the new time array.(a time data for each sensor)
    time_in_number = (df.index.values - df.index.values.astype("datetime64[D]")) / np.timedelta64(1, "D")
    time_array = np.tile(time_in_number, [1, n_nodes, 1]).transpose((2, 1, 0))
    data_list.append(time_array)
    data = np.concatenate(data_list, axis=-1)

    #Split datalist by x,ys' offset.
    # epoch_len = num_samples + min(x_offsets) - max(y_offsets)
    x, y = [], []
    # t is the index of the last observation.
    min_t = abs(min(x_offsets))
    max_t = abs(n_samples - abs(max(y_offsets)))
    for t in range(min_t, max_t):
        x_t = data[t + x_offsets, ...]
        y_t = data[t + y_offsets, ...]
        x.append(x_t)
        y.append(y_t)
    x = np.stack(x, axis=0)
    y = np.stack(y, axis=0)
    return x, y

In [146]:
h5_test = HDFStore('pems_all_2022_updated.h5')
df_test = h5_test['speed']

In [176]:
a, b = generate_data(df_test, 12, 12)

In [155]:
#a, b
#x.shape, y.shape
#y

((51626, 12, 319, 2), (51626, 12, 319, 2))

In [177]:
a.shape, b.shape

((51626, 12, 319, 2), (51626, 12, 319, 2))

In [178]:
num_samples = a.shape[0]
num_test = round(num_samples * 0.2)
num_train = round(num_samples * 0.7)
num_val = num_samples - num_test - num_train
num_test, num_train, num_val

(10325, 36138, 5163)

In [ ]:
x_train, y_train = x[:num_train], y[:num_train]
# val
x_val = x[num_train: num_train + num_val]
y_val = y[num_train: num_train + num_val]
# test
x_test, y_test = x[-num_test:], y[-num_test:]



In [190]:
def split_dataset(x, y):
    num_samples = x.shape[0]
    num_test = round(num_samples * 0.2)
    num_train = round(num_samples * 0.7)
    num_val = num_samples - num_test - num_train
    num_test, num_train, num_val
    train_list, val_list, test_list = [], [], []
    
    x_train, y_train = x[:num_train], y[:num_train]
    # val
    x_val = x[num_train: num_train + num_val]
    y_val = y[num_train: num_train + num_val]
    # test
    x_test, y_test = x[-num_test:], y[-num_test:]

    train_list.append(x_train)
    train_list.append(y_train)
    #print(train_list)
    
    val_list.append(x_val)
    val_list.append(y_val)
    #print(val_list)
    
    test_list.append(x_test)
    test_list.append(y_test)
    #print(test_list)
    
    return train_list, val_list, test_list

In [191]:
train,v,test = split_dataset(a, b)

In [201]:
#train[0].shape, train[1].shape
#v[0].shape, v[1].shape
#test[0].shape, test[1].shape
train[0]
#train[1].shape

array([[[[7.18000000e+01, 0.00000000e+00],
         [6.81000000e+01, 0.00000000e+00],
         [6.81000000e+01, 0.00000000e+00],
         ...,
         [6.83000000e+01, 0.00000000e+00],
         [7.14000000e+01, 0.00000000e+00],
         [6.78000000e+01, 0.00000000e+00]],

        [[7.11000000e+01, 3.47222222e-03],
         [6.80000000e+01, 3.47222222e-03],
         [6.81000000e+01, 3.47222222e-03],
         ...,
         [6.82000000e+01, 3.47222222e-03],
         [7.13000000e+01, 3.47222222e-03],
         [6.84000000e+01, 3.47222222e-03]],

        [[7.09000000e+01, 6.94444444e-03],
         [6.80000000e+01, 6.94444444e-03],
         [6.81000000e+01, 6.94444444e-03],
         ...,
         [6.80000000e+01, 6.94444444e-03],
         [7.10000000e+01, 6.94444444e-03],
         [6.75000000e+01, 6.94444444e-03]],

        ...,

        [[7.11000000e+01, 3.12500000e-02],
         [6.77000000e+01, 3.12500000e-02],
         [6.73000000e+01, 3.12500000e-02],
         ...,
         [6.86000000e

In [202]:
train[1]

array([[[[7.07000000e+01, 4.16666667e-02],
         [6.79000000e+01, 4.16666667e-02],
         [6.78000000e+01, 4.16666667e-02],
         ...,
         [6.88000000e+01, 4.16666667e-02],
         [7.12000000e+01, 4.16666667e-02],
         [6.74000000e+01, 4.16666667e-02]],

        [[7.08000000e+01, 4.51388889e-02],
         [6.79000000e+01, 4.51388889e-02],
         [6.73000000e+01, 4.51388889e-02],
         ...,
         [6.93000000e+01, 4.51388889e-02],
         [7.10000000e+01, 4.51388889e-02],
         [6.74000000e+01, 4.51388889e-02]],

        [[7.14000000e+01, 4.86111111e-02],
         [6.77000000e+01, 4.86111111e-02],
         [6.76000000e+01, 4.86111111e-02],
         ...,
         [6.81000000e+01, 4.86111111e-02],
         [7.03000000e+01, 4.86111111e-02],
         [6.78000000e+01, 4.86111111e-02]],

        ...,

        [[7.13000000e+01, 7.29166667e-02],
         [6.78000000e+01, 7.29166667e-02],
         [6.79000000e+01, 7.29166667e-02],
         ...,
         [6.87000000e